name: CICD

env:
  MIN_SUPPORTED_RUST_VERSION: "1.46.0"
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test_with_system_config:
    name: Run tests with system wide configuration
    runs-on: ubuntu-20.04
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Prepare environment variables
      run: |
        echo "BAT_SYSTEM_CONFIG_PREFIX=$GITHUB_WORKSPACE/tests/examples/system_config" >> $GITHUB_ENV
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
    - name: Build and install bat
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --locked --path .
    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --locked --test system_wide_config -- --ignored

